/*
 * catalogue-api
 * NHS Digital GP IT Futures Buying Catalog API
 *
 * OpenAPI spec version: 1.0.0-private-beta
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.CapabilityMapping;
import io.swagger.client.model.Standards;
import java.util.ArrayList;
import java.util.List;

/**
 * All CapabilityMapping with all corresponding Standard
 */
@ApiModel(description = "All CapabilityMapping with all corresponding Standard")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-29T15:45:36.951Z")
public class CapabilityMappings {
  @JsonProperty("capabilityMapping")
  private List<CapabilityMapping> capabilityMapping = null;

  @JsonProperty("standard")
  private List<Standards> standard = null;

  public CapabilityMappings capabilityMapping(List<CapabilityMapping> capabilityMapping) {
    this.capabilityMapping = capabilityMapping;
    return this;
  }

  public CapabilityMappings addCapabilityMappingItem(CapabilityMapping capabilityMappingItem) {
    if (this.capabilityMapping == null) {
      this.capabilityMapping = new ArrayList<CapabilityMapping>();
    }
    this.capabilityMapping.add(capabilityMappingItem);
    return this;
  }

   /**
   * NHSD.GPITF.BuyingCatalog.Models.Porcelain.CapabilityMappings.CapabilityMapping
   * @return capabilityMapping
  **/
  @ApiModelProperty(value = "NHSD.GPITF.BuyingCatalog.Models.Porcelain.CapabilityMappings.CapabilityMapping")
  public List<CapabilityMapping> getCapabilityMapping() {
    return capabilityMapping;
  }

  public void setCapabilityMapping(List<CapabilityMapping> capabilityMapping) {
    this.capabilityMapping = capabilityMapping;
  }

  public CapabilityMappings standard(List<Standards> standard) {
    this.standard = standard;
    return this;
  }

  public CapabilityMappings addStandardItem(Standards standardItem) {
    if (this.standard == null) {
      this.standard = new ArrayList<Standards>();
    }
    this.standard.add(standardItem);
    return this;
  }

   /**
   * A list of NHSD.GPITF.BuyingCatalog.Models.Porcelain.CapabilityMappings.Standard
   * @return standard
  **/
  @ApiModelProperty(value = "A list of NHSD.GPITF.BuyingCatalog.Models.Porcelain.CapabilityMappings.Standard")
  public List<Standards> getStandard() {
    return standard;
  }

  public void setStandard(List<Standards> standard) {
    this.standard = standard;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CapabilityMappings capabilityMappings = (CapabilityMappings) o;
    return Objects.equals(this.capabilityMapping, capabilityMappings.capabilityMapping) &&
        Objects.equals(this.standard, capabilityMappings.standard);
  }

  @Override
  public int hashCode() {
    return Objects.hash(capabilityMapping, standard);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CapabilityMappings {\n");
    
    sb.append("    capabilityMapping: ").append(toIndentedString(capabilityMapping)).append("\n");
    sb.append("    standard: ").append(toIndentedString(standard)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

