/*
 * catalogue-api
 * NHS Digital GP IT Futures Buying Catalog API
 *
 * OpenAPI spec version: 1.0.0-private-beta
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.BlobInfo;
import java.util.ArrayList;
import java.util.List;

/**
 * Mapping between a claimed capability or standard and it&#39;s corresponding  folders and files in blob datastore
 */
@ApiModel(description = "Mapping between a claimed capability or standard and it's corresponding  folders and files in blob datastore")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-02-27T11:46:50.314Z")
public class ClaimBlobInfoMap {
  @JsonProperty("claimId")
  private String claimId = null;

  @JsonProperty("blobInfos")
  private List<BlobInfo> blobInfos = null;

  public ClaimBlobInfoMap claimId(String claimId) {
    this.claimId = claimId;
    return this;
  }

   /**
   * Unique identifier of claimed capability or standard
   * @return claimId
  **/
  @ApiModelProperty(value = "Unique identifier of claimed capability or standard")
  public String getClaimId() {
    return claimId;
  }

  public void setClaimId(String claimId) {
    this.claimId = claimId;
  }

  public ClaimBlobInfoMap blobInfos(List<BlobInfo> blobInfos) {
    this.blobInfos = blobInfos;
    return this;
  }

  public ClaimBlobInfoMap addBlobInfosItem(BlobInfo blobInfosItem) {
    if (this.blobInfos == null) {
      this.blobInfos = new ArrayList<BlobInfo>();
    }
    this.blobInfos.add(blobInfosItem);
    return this;
  }

   /**
   * List of folders and files associated with this claimed capability or standard
   * @return blobInfos
  **/
  @ApiModelProperty(value = "List of folders and files associated with this claimed capability or standard")
  public List<BlobInfo> getBlobInfos() {
    return blobInfos;
  }

  public void setBlobInfos(List<BlobInfo> blobInfos) {
    this.blobInfos = blobInfos;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClaimBlobInfoMap claimBlobInfoMap = (ClaimBlobInfoMap) o;
    return Objects.equals(this.claimId, claimBlobInfoMap.claimId) &&
        Objects.equals(this.blobInfos, claimBlobInfoMap.blobInfos);
  }

  @Override
  public int hashCode() {
    return Objects.hash(claimId, blobInfos);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClaimBlobInfoMap {\n");
    
    sb.append("    claimId: ").append(toIndentedString(claimId)).append("\n");
    sb.append("    blobInfos: ").append(toIndentedString(blobInfos)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

