/*
 * catalogue-api
 * NHS Digital GP IT Futures Buying Catalog API
 *
 * OpenAPI spec version: 1.0.0-private-beta
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * A means of communicating with an organisation, typically a person, email address, telephone number etc.  Standard MS Dynamics CRM entity
 */
@ApiModel(description = "A means of communicating with an organisation, typically a person, email address, telephone number etc.  Standard MS Dynamics CRM entity")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-11T12:47:15.885Z")
public class Contacts {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("organisationId")
  private String organisationId = null;

  @JsonProperty("firstName")
  private String firstName = null;

  @JsonProperty("lastName")
  private String lastName = null;

  @JsonProperty("emailAddress1")
  private String emailAddress1 = null;

  @JsonProperty("phoneNumber1")
  private String phoneNumber1 = null;

  public Contacts id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Unique identifier of entity
   * @return id
  **/
  @ApiModelProperty(required = true, value = "Unique identifier of entity")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Contacts organisationId(String organisationId) {
    this.organisationId = organisationId;
    return this;
  }

   /**
   * Unique identifier of organisation
   * @return organisationId
  **/
  @ApiModelProperty(required = true, value = "Unique identifier of organisation")
  public String getOrganisationId() {
    return organisationId;
  }

  public void setOrganisationId(String organisationId) {
    this.organisationId = organisationId;
  }

  public Contacts firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * First name of contact
   * @return firstName
  **/
  @ApiModelProperty(value = "First name of contact")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public Contacts lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Last name of contact
   * @return lastName
  **/
  @ApiModelProperty(value = "Last name of contact")
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public Contacts emailAddress1(String emailAddress1) {
    this.emailAddress1 = emailAddress1;
    return this;
  }

   /**
   * Primary email address of contact
   * @return emailAddress1
  **/
  @ApiModelProperty(required = true, value = "Primary email address of contact")
  public String getEmailAddress1() {
    return emailAddress1;
  }

  public void setEmailAddress1(String emailAddress1) {
    this.emailAddress1 = emailAddress1;
  }

  public Contacts phoneNumber1(String phoneNumber1) {
    this.phoneNumber1 = phoneNumber1;
    return this;
  }

   /**
   * Primary phone number of contact
   * @return phoneNumber1
  **/
  @ApiModelProperty(value = "Primary phone number of contact")
  public String getPhoneNumber1() {
    return phoneNumber1;
  }

  public void setPhoneNumber1(String phoneNumber1) {
    this.phoneNumber1 = phoneNumber1;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Contacts contacts = (Contacts) o;
    return Objects.equals(this.id, contacts.id) &&
        Objects.equals(this.organisationId, contacts.organisationId) &&
        Objects.equals(this.firstName, contacts.firstName) &&
        Objects.equals(this.lastName, contacts.lastName) &&
        Objects.equals(this.emailAddress1, contacts.emailAddress1) &&
        Objects.equals(this.phoneNumber1, contacts.phoneNumber1);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, organisationId, firstName, lastName, emailAddress1, phoneNumber1);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Contacts {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    organisationId: ").append(toIndentedString(organisationId)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    emailAddress1: ").append(toIndentedString(emailAddress1)).append("\n");
    sb.append("    phoneNumber1: ").append(toIndentedString(phoneNumber1)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

