/*
 * catalogue-api
 * NHS Digital GP IT Futures Buying Catalog API
 *
 * OpenAPI spec version: 1.0.0-private-beta
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.StringSegment;

/**
 * EntityTagHeaderValue
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-29T15:45:36.951Z")
public class EntityTagHeaderValue {
  @JsonProperty("tag")
  private StringSegment tag = null;

  @JsonProperty("isWeak")
  private Boolean isWeak = null;

   /**
   * Get tag
   * @return tag
  **/
  @ApiModelProperty(value = "")
  public StringSegment getTag() {
    return tag;
  }

   /**
   * Get isWeak
   * @return isWeak
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsWeak() {
    return isWeak;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EntityTagHeaderValue entityTagHeaderValue = (EntityTagHeaderValue) o;
    return Objects.equals(this.tag, entityTagHeaderValue.tag) &&
        Objects.equals(this.isWeak, entityTagHeaderValue.isWeak);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tag, isWeak);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntityTagHeaderValue {\n");
    
    sb.append("    tag: ").append(toIndentedString(tag)).append("\n");
    sb.append("    isWeak: ").append(toIndentedString(isWeak)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

