/*
 * catalogue-api
 * NHS Digital GP IT Futures Buying Catalog API
 *
 * OpenAPI spec version: 1.0.0-private-beta
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * A &#39;Supplier&#39; is a company who supplies ‘solutions’ to NHS buyers.  A &#39;Buyer&#39; is a company who purchases &#39;solutions&#39; from a &#39;Supplier&#39;.  An &#39;Admin&#39; is a company, typically NHS Digital, who has ultimate control over all information in the Buying Catalog.  Standard MS Dynamics CRM entity
 */
@ApiModel(description = "A 'Supplier' is a company who supplies ‘solutions’ to NHS buyers.  A 'Buyer' is a company who purchases 'solutions' from a 'Supplier'.  An 'Admin' is a company, typically NHS Digital, who has ultimate control over all information in the Buying Catalog.  Standard MS Dynamics CRM entity")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-01-29T15:45:36.951Z")
public class Organisations {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("odsCode")
  private String odsCode = null;

  @JsonProperty("primaryRoleId")
  private String primaryRoleId = null;

  @JsonProperty("status")
  private String status = null;

  @JsonProperty("description")
  private String description = null;

  public Organisations id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Unique identifier of entity
   * @return id
  **/
  @ApiModelProperty(required = true, value = "Unique identifier of entity")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Organisations name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of a company, as displayed to the user
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Name of a company, as displayed to the user")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Organisations odsCode(String odsCode) {
    this.odsCode = odsCode;
    return this;
  }

   /**
   * ODS code for company
   * @return odsCode
  **/
  @ApiModelProperty(required = true, value = "ODS code for company")
  public String getOdsCode() {
    return odsCode;
  }

  public void setOdsCode(String odsCode) {
    this.odsCode = odsCode;
  }

  public Organisations primaryRoleId(String primaryRoleId) {
    this.primaryRoleId = primaryRoleId;
    return this;
  }

   /**
   * Primary ODS role code for company  Suppliers have a primary role of \&quot;RO92\&quot;
   * @return primaryRoleId
  **/
  @ApiModelProperty(required = true, value = "Primary ODS role code for company  Suppliers have a primary role of \"RO92\"")
  public String getPrimaryRoleId() {
    return primaryRoleId;
  }

  public void setPrimaryRoleId(String primaryRoleId) {
    this.primaryRoleId = primaryRoleId;
  }

  public Organisations status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Operational status of company  Typically:  \&quot;Active\&quot;, \&quot;Inactive\&quot;
   * @return status
  **/
  @ApiModelProperty(required = true, value = "Operational status of company  Typically:  \"Active\", \"Inactive\"")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Organisations description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Information about company
   * @return description
  **/
  @ApiModelProperty(value = "Information about company")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Organisations organisations = (Organisations) o;
    return Objects.equals(this.id, organisations.id) &&
        Objects.equals(this.name, organisations.name) &&
        Objects.equals(this.odsCode, organisations.odsCode) &&
        Objects.equals(this.primaryRoleId, organisations.primaryRoleId) &&
        Objects.equals(this.status, organisations.status) &&
        Objects.equals(this.description, organisations.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, odsCode, primaryRoleId, status, description);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Organisations {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    odsCode: ").append(toIndentedString(odsCode)).append("\n");
    sb.append("    primaryRoleId: ").append(toIndentedString(primaryRoleId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

