/*
 * catalogue-api
 * NHS Digital GP IT Futures Buying Catalog API
 *
 * OpenAPI spec version: 1.0.0-private-beta
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.SolutionEx;

/**
 * A SolutionEx and an indication of its relevance (Distance)
 */
@ApiModel(description = "A SolutionEx and an indication of its relevance (Distance)")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-04-09T09:44:06.853Z")
public class SearchResult {
  @JsonProperty("solutionEx")
  private SolutionEx solutionEx = null;

  @JsonProperty("distance")
  private Integer distance = null;

  public SearchResult solutionEx(SolutionEx solutionEx) {
    this.solutionEx = solutionEx;
    return this;
  }

   /**
   * SolutionEx
   * @return solutionEx
  **/
  @ApiModelProperty(value = "SolutionEx")
  public SolutionEx getSolutionEx() {
    return solutionEx;
  }

  public void setSolutionEx(SolutionEx solutionEx) {
    this.solutionEx = solutionEx;
  }

  public SearchResult distance(Integer distance) {
    this.distance = distance;
    return this;
  }

   /**
   * How far away the SolutionEx is from ideal:    zero     &#x3D;&amp;gt; SolutionEx has exactly capabilities required    positive &#x3D;&amp;gt; SolutionEx has more capabilities than required    negative &#x3D;&amp;gt; SolutionEx has less capabilities than required
   * @return distance
  **/
  @ApiModelProperty(value = "How far away the SolutionEx is from ideal:    zero     =&gt; SolutionEx has exactly capabilities required    positive =&gt; SolutionEx has more capabilities than required    negative =&gt; SolutionEx has less capabilities than required")
  public Integer getDistance() {
    return distance;
  }

  public void setDistance(Integer distance) {
    this.distance = distance;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchResult searchResult = (SearchResult) o;
    return Objects.equals(this.solutionEx, searchResult.solutionEx) &&
        Objects.equals(this.distance, searchResult.distance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(solutionEx, distance);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchResult {\n");
    
    sb.append("    solutionEx: ").append(toIndentedString(solutionEx)).append("\n");
    sb.append("    distance: ").append(toIndentedString(distance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

