/*
 * catalogue-api
 * NHS Digital GP IT Futures Buying Catalog API
 *
 * OpenAPI spec version: 1.0.0-private-beta
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.CapabilitiesImplementedReviews;
import io.swagger.client.model.PaginatedListIEnumerableCapabilitiesImplementedReviews;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CapabilitiesImplementedReviewsApi
 */
@Ignore
public class CapabilitiesImplementedReviewsApiTest {

    private final CapabilitiesImplementedReviewsApi api = new CapabilitiesImplementedReviewsApi();

    
    /**
     * Get all Reviews for a CapabilitiesImplemented  Each list is a distinct &#39;chain&#39; of Review ie original Review with all subsequent Review  The first item in each &#39;chain&#39; is the most current Review.  The last item in each &#39;chain&#39; is the original Review.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiCapabilitiesImplementedReviewsByEvidenceByEvidenceIdGetTest() {
        String evidenceId = null;
        Integer pageIndex = null;
        Integer pageSize = null;
        PaginatedListIEnumerableCapabilitiesImplementedReviews response = api.apiCapabilitiesImplementedReviewsByEvidenceByEvidenceIdGet(evidenceId, pageIndex, pageSize);

        // TODO: test validations
    }
    
    /**
     * Create a new Review for a CapabilitiesImplemented
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiCapabilitiesImplementedReviewsPostTest() {
        CapabilitiesImplementedReviews review = null;
        CapabilitiesImplementedReviews response = api.apiCapabilitiesImplementedReviewsPost(review);

        // TODO: test validations
    }
    
}
