/*
 * catalogue-api
 * NHS Digital GP IT Futures Buying Catalog API
 *
 * OpenAPI spec version: 1.0.0-private-beta
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.CapabilitiesImplemented;
import io.swagger.client.model.PaginatedListCapabilitiesImplemented;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CapabilitiesImplementedApi
 */
@Ignore
public class CapabilitiesImplementedApiTest {

    private final CapabilitiesImplementedApi api = new CapabilitiesImplementedApi();

    
    /**
     * Retrieve claim, given the claim’s CRM identifier
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiCapabilitiesImplementedByIdGetTest() {
        String id = null;
        CapabilitiesImplemented response = api.apiCapabilitiesImplementedByIdGet(id);

        // TODO: test validations
    }
    
    /**
     * Retrieve all claimed capabilities for a solution in a paged list,  given the solution’s CRM identifier
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiCapabilitiesImplementedBySolutionBySolutionIdGetTest() {
        String solutionId = null;
        Integer pageIndex = null;
        Integer pageSize = null;
        PaginatedListCapabilitiesImplemented response = api.apiCapabilitiesImplementedBySolutionBySolutionIdGet(solutionId, pageIndex, pageSize);

        // TODO: test validations
    }
    
    /**
     * Delete an existing claimed capability for a solution
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiCapabilitiesImplementedDeleteTest() {
        CapabilitiesImplemented claimedcapability = null;
        api.apiCapabilitiesImplementedDelete(claimedcapability);

        // TODO: test validations
    }
    
    /**
     * Create a new claimed capability for a solution
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiCapabilitiesImplementedPostTest() {
        CapabilitiesImplemented claimedcapability = null;
        CapabilitiesImplemented response = api.apiCapabilitiesImplementedPost(claimedcapability);

        // TODO: test validations
    }
    
    /**
     * Update an existing claimed capability with new information
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiCapabilitiesImplementedPutTest() {
        CapabilitiesImplemented claimedcapability = null;
        api.apiCapabilitiesImplementedPut(claimedcapability);

        // TODO: test validations
    }
    
}
