/*
 * catalogue-api
 * NHS Digital GP IT Futures Buying Catalog API
 *
 * OpenAPI spec version: 1.0.0-private-beta
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.CapabilityMappings;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CapabilityMappingsApi
 */
@Ignore
public class CapabilityMappingsApiTest {

    private final CapabilityMappingsApi api = new CapabilityMappingsApi();

    
    /**
     * Get capabilities with a list of corresponding, optional standards
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiPorcelainCapabilityMappingsGetTest() {
        CapabilityMappings response = api.apiPorcelainCapabilityMappingsGet();

        // TODO: test validations
    }
    
}
