/*
 * catalogue-api
 * NHS Digital GP IT Futures Buying Catalog API
 *
 * OpenAPI spec version: 1.0.0-private-beta
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EvidenceBlobStoreApi
 */
@Ignore
public class EvidenceBlobStoreApiTest {

    private final EvidenceBlobStoreApi api = new EvidenceBlobStoreApi();

    
    /**
     * Create server side folder structure for specified solution
     *
     * Server side folder structure is something like:  --Organisation  ----Solution  ------Capability Evidence  --------Appointment Management - Citizen  --------Appointment Management - GP  --------Clinical Decision Support  --------[all other claimed capabilities]    Will be done automagically when solution status changes to SolutionStatus.CapabilitiesAssessment
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiEvidenceBlobStorePrepareForSolutionBySolutionIdPutTest() {
        String solutionId = null;
        api.apiEvidenceBlobStorePrepareForSolutionBySolutionIdPut(solutionId);

        // TODO: test validations
    }
    
}
