/*
 * catalogue-api
 * NHS Digital GP IT Futures Buying Catalog API
 *
 * OpenAPI spec version: 1.0.0-private-beta
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.Frameworks;
import io.swagger.client.model.PaginatedListFrameworks;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FrameworksApi
 */
@Ignore
public class FrameworksApiTest {

    private final FrameworksApi api = new FrameworksApi();

    
    /**
     * Get existing framework/s which have the given capability
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiFrameworksByCapabilityByCapabilityIdGetTest() {
        String capabilityId = null;
        Integer pageIndex = null;
        Integer pageSize = null;
        PaginatedListFrameworks response = api.apiFrameworksByCapabilityByCapabilityIdGet(capabilityId, pageIndex, pageSize);

        // TODO: test validations
    }
    
    /**
     * Get an existing framework given its CRM identifier  Typically used to retrieve previous version
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiFrameworksByIdByIdGetTest() {
        String id = null;
        Frameworks response = api.apiFrameworksByIdByIdGet(id);

        // TODO: test validations
    }
    
    /**
     * Get existing framework/s on which a solution was onboarded, given the CRM identifier of the solution
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiFrameworksBySolutionBySolutionIdGetTest() {
        String solutionId = null;
        Integer pageIndex = null;
        Integer pageSize = null;
        PaginatedListFrameworks response = api.apiFrameworksBySolutionBySolutionIdGet(solutionId, pageIndex, pageSize);

        // TODO: test validations
    }
    
    /**
     * Get existing framework/s which have the given standard
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiFrameworksByStandardByStandardIdGetTest() {
        String standardId = null;
        Integer pageIndex = null;
        Integer pageSize = null;
        PaginatedListFrameworks response = api.apiFrameworksByStandardByStandardIdGet(standardId, pageIndex, pageSize);

        // TODO: test validations
    }
    
    /**
     * Retrieve all current frameworks in a paged list
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiFrameworksGetTest() {
        Integer pageIndex = null;
        Integer pageSize = null;
        PaginatedListFrameworks response = api.apiFrameworksGet(pageIndex, pageSize);

        // TODO: test validations
    }
    
}
