/*
 * catalogue-api
 * NHS Digital GP IT Futures Buying Catalog API
 *
 * OpenAPI spec version: 1.0.0-private-beta
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for LinkManagerApi
 */
@Ignore
public class LinkManagerApiTest {

    private final LinkManagerApi api = new LinkManagerApi();

    
    /**
     * Create a link between a Framework and a Solution
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiLinkManagerFrameworkSolutionCreateByFrameworkIdBySolutionIdPostTest() {
        String frameworkId = null;
        String solutionId = null;
        api.apiLinkManagerFrameworkSolutionCreateByFrameworkIdBySolutionIdPost(frameworkId, solutionId);

        // TODO: test validations
    }
    
}
