/*
 * catalogue-api
 * NHS Digital GP IT Futures Buying Catalog API
 *
 * OpenAPI spec version: 1.0.0-private-beta
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.SolutionEx;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SolutionsExApi
 */
@Ignore
public class SolutionsExApiTest {

    private final SolutionsExApi api = new SolutionsExApi();

    
    /**
     * Get a Solution with a list of corresponding TechnicalContact, ClaimedCapability, ClaimedStandard et al
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiPorcelainSolutionsExBySolutionBySolutionIdGetTest() {
        String solutionId = null;
        SolutionEx response = api.apiPorcelainSolutionsExBySolutionBySolutionIdGet(solutionId);

        // TODO: test validations
    }
    
    /**
     * Update an existing Solution, TechnicalContact, ClaimedCapability, ClaimedStandard et al with new information
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiPorcelainSolutionsExUpdatePutTest() {
        SolutionEx solnEx = null;
        api.apiPorcelainSolutionsExUpdatePut(solnEx);

        // TODO: test validations
    }
    
}
