/*
 * catalogue-api
 * NHS Digital GP IT Futures Buying Catalog API
 *
 * OpenAPI spec version: 1.0.0-private-beta
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.PaginatedListIEnumerableStandardsApplicableEvidence;
import io.swagger.client.model.StandardsApplicableEvidence;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for StandardsApplicableEvidenceApi
 */
@Ignore
public class StandardsApplicableEvidenceApiTest {

    private final StandardsApplicableEvidenceApi api = new StandardsApplicableEvidenceApi();

    
    /**
     * Get all Evidence for the given Claim  Each list is a distinct &#39;chain&#39; of Evidence ie original Evidence with all subsequent Evidence  The first item in each &#39;chain&#39; is the most current Evidence.  The last item in each &#39;chain&#39; is the original Evidence.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiStandardsApplicableEvidenceByClaimByClaimIdGetTest() {
        String claimId = null;
        Integer pageIndex = null;
        Integer pageSize = null;
        PaginatedListIEnumerableStandardsApplicableEvidence response = api.apiStandardsApplicableEvidenceByClaimByClaimIdGet(claimId, pageIndex, pageSize);

        // TODO: test validations
    }
    
    /**
     * Create a new evidence
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiStandardsApplicableEvidencePostTest() {
        StandardsApplicableEvidence evidence = null;
        StandardsApplicableEvidence response = api.apiStandardsApplicableEvidencePost(evidence);

        // TODO: test validations
    }
    
}
