/*
 * catalogue-api
 * NHS Digital GP IT Futures Buying Catalog API
 *
 * OpenAPI spec version: 1.0.0-private-beta
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.PaginatedListIEnumerableStandardsApplicableReviews;
import io.swagger.client.model.StandardsApplicableReviews;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for StandardsApplicableReviewsApi
 */
@Ignore
public class StandardsApplicableReviewsApiTest {

    private final StandardsApplicableReviewsApi api = new StandardsApplicableReviewsApi();

    
    /**
     * Get all Reviews for a StandardsApplicable  Each list is a distinct &#39;chain&#39; of Review ie original Review with all subsequent Review  The first item in each &#39;chain&#39; is the most current Review.  The last item in each &#39;chain&#39; is the original Review.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiStandardsApplicableReviewsByEvidenceByEvidenceIdGetTest() {
        String evidenceId = null;
        Integer pageIndex = null;
        Integer pageSize = null;
        PaginatedListIEnumerableStandardsApplicableReviews response = api.apiStandardsApplicableReviewsByEvidenceByEvidenceIdGet(evidenceId, pageIndex, pageSize);

        // TODO: test validations
    }
    
    /**
     * Create a new Review for a StandardsApplicable
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiStandardsApplicableReviewsPostTest() {
        StandardsApplicableReviews review = null;
        StandardsApplicableReviews response = api.apiStandardsApplicableReviewsPost(review);

        // TODO: test validations
    }
    
}
