/*
 * catalogue-api
 * NHS Digital GP IT Futures Buying Catalog API
 *
 * OpenAPI spec version: 1.0.0-private-beta
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.PaginatedListStandards;
import io.swagger.client.model.Standards;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for StandardsApi
 */
@Ignore
public class StandardsApiTest {

    private final StandardsApi api = new StandardsApi();

    
    /**
     * Get existing/optional Standard/s which are in the given Capability
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiStandardsByCapabilityByCapabilityIdGetTest() {
        String capabilityId = null;
        Boolean isOptional = null;
        Integer pageIndex = null;
        Integer pageSize = null;
        PaginatedListStandards response = api.apiStandardsByCapabilityByCapabilityIdGet(capabilityId, isOptional, pageIndex, pageSize);

        // TODO: test validations
    }
    
    /**
     * Get existing Standard/s which are in the given Framework
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiStandardsByFrameworkByFrameworkIdGetTest() {
        String frameworkId = null;
        Integer pageIndex = null;
        Integer pageSize = null;
        PaginatedListStandards response = api.apiStandardsByFrameworkByFrameworkIdGet(frameworkId, pageIndex, pageSize);

        // TODO: test validations
    }
    
    /**
     * Get an existing standard given its CRM identifier  Typically used to retrieve previous version
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiStandardsByIdByIdGetTest() {
        String id = null;
        Standards response = api.apiStandardsByIdByIdGet(id);

        // TODO: test validations
    }
    
    /**
     * Get several existing Standards given their CRM identifiers
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiStandardsByIdsPostTest() {
        List<String> ids = null;
        List<Standards> response = api.apiStandardsByIdsPost(ids);

        // TODO: test validations
    }
    
    /**
     * Retrieve all current standards in a paged list
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiStandardsGetTest() {
        Integer pageIndex = null;
        Integer pageSize = null;
        PaginatedListStandards response = api.apiStandardsGet(pageIndex, pageSize);

        // TODO: test validations
    }
    
}
