/*
 * catalogue-api
 * NHS Digital GP IT Futures Buying Catalog API
 *
 * OpenAPI spec version: 1.0.0-private-beta
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.PaginatedListTechnicalContacts;
import io.swagger.client.model.TechnicalContacts;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TechnicalContactsApi
 */
@Ignore
public class TechnicalContactsApiTest {

    private final TechnicalContactsApi api = new TechnicalContactsApi();

    
    /**
     * Retrieve all Technical Contacts for a solution in a paged list,  given the solution’s CRM identifier
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiTechnicalContactsBySolutionBySolutionIdGetTest() {
        String solutionId = null;
        Integer pageIndex = null;
        Integer pageSize = null;
        PaginatedListTechnicalContacts response = api.apiTechnicalContactsBySolutionBySolutionIdGet(solutionId, pageIndex, pageSize);

        // TODO: test validations
    }
    
    /**
     * Delete an existing Technical Contact for a Solution
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiTechnicalContactsDeleteTest() {
        TechnicalContacts techCont = null;
        api.apiTechnicalContactsDelete(techCont);

        // TODO: test validations
    }
    
    /**
     * Create a new Technical Contact for a Solution
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiTechnicalContactsPostTest() {
        TechnicalContacts techCont = null;
        TechnicalContacts response = api.apiTechnicalContactsPost(techCont);

        // TODO: test validations
    }
    
    /**
     * Update a Technical Contact with new information
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void apiTechnicalContactsPutTest() {
        TechnicalContacts techCont = null;
        api.apiTechnicalContactsPut(techCont);

        // TODO: test validations
    }
    
}
